theme = "kanagawa"

[editor]
true-color = true
end-of-line-diagnostics = "hint"
bufferline = "multiple"
default-line-ending = "lf"
default-yank-register = "+"
completion-trigger-len = 1


[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
parents = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
tab = "goto_next_function"
S-tab = "goto_prev_function"

[keys.normal.space]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]


# [keys.normal]
# C-y = [
#   ':sh rm -f /tmp/unique-file',
#   ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
#   ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
#   ':open %sh{cat /tmp/unique-file}',
#   ':redraw',
# ]
