
# PYTHON
[[language]]
name = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json", ".venv/"]
comment-token = "#"
# language-servers = [ "basedpyright", "ruff" ]
language-servers = [ "basedpyright" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true


[language.formatter]
# command = "ruff"
# args = [
#   "format",
#   "-"
# ]
command = "zsh"
args = ["-c", "ruff check --select I --fix - | ruff format -"]


[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
except-features = ["format", "code-action"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
# typeCheckingMode = "basic"
# diagnosticMode = "openFilesOnly"

# [language-server.ruff]
# # command = "ruff-lsp"
# command = "ruff"
# args = ["server", "-q", "--preview"]


# TYPST
[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typ(st)?"
file-types = ["typst", "typ"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["tinymist"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[language-server.tinymist]
command = "tinymist"
config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"]}
formatterMode = "typstyle"

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "master" }


[[language]]
name = "latex"
scope = "source.tex"
injection-regex = "tex"
file-types = ["tex", "sty", "cls", "Rd", "bbx", "cbx"]
comment-token = "%"
language-servers = [ "texlab" ]
indent = { tab-width = 4, unit = "\t" }

[language.auto-pairs]
'$' = '$'
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

# [language-server.texlab.config.texlab.forwardSearch]
# executable = "zathura"
# args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.build]
# auxDirectory = "build"
# logDirectory = "build"
# pdfDirectory = "build"
onSave = true

executable = "tectonic"
args = [
 "-X",
 "compile",
 "%f",
 "--keep-logs",
 "--keep-intermediates",
 "--synctex",
 ]
# forwardSearchAfter = true
 # "--outdir=build",

