
# PYTHON
[[language]]
name = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json", ".venv/"]
comment-token = "#"
# language-servers = [ "basedpyright", "ruff" ]
language-servers = [ "basedpyright" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true


[language.formatter]
# command = "ruff"
# args = [
#   "format",
#   "-"
# ]
command = "zsh"
args = ["-c", "ruff check --select I --fix - | ruff format -"]




[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
except-features = ["format", "code-action"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
# typeCheckingMode = "basic"
# diagnosticMode = "openFilesOnly"

# [language-server.ruff]
# # command = "ruff-lsp"
# command = "ruff"
# args = ["server", "-q", "--preview"]


# TYPST
[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typ(st)?"
file-types = ["typst", "typ"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["tinymist"]
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType" }

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "13863ddcbaa7b68ee6221cea2e3143415e64aea4" }
